# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  docker-runner:
    environment:
      PROJECT_NAME: Projet1-Team-1
    docker:
      - image: circleci/node:12.13.0
      - image: postgres
      - image: redis
  docker-publisher:
    environment:
      PROJECT_NAME: Projet1-Team-1
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  install:
    executor: docker-runner
    steps:
      - checkout
      - run:
          name: install package
          command: npm ci
  test :
    executor: docker-runner
    steps:
      - run: echo "A Test"
  
  publish-image :
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Build Docker Image
          command: docker build -t  ${PROJECT_NAME}:latest .
      # - run:
      #     name: Archive Image
      #     command: docker save -o ./image.tar ${PROJECT_NAME}:latest
      - run:
          name: Connect to dockerhub
          command: docker login --username=${DH_USERNAME} --email=${DH_EMAIL} --password=${DH_PASSWORD}
      -run:
          name: Push on dockerhub
          command: docker push ${DH_USERNAME}/${PROJECT_NAME}:latest


workflows:
  version: 2
  build-infra:
    jobs:
      - install:
      - test:
          requires:
            install
      - publish-image:
          requires:
            test