# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  docker-runner:
    environment:
      PROJECT_NAME: Projet1-Team-1
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  push:
    executor: docker-runner
    steps:
      - run: echo "A change occurs"
  
  install:
    executor: docker-runner
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build infra
          command: docker-compose build
      - run:
          name: up infra
          command: docker-compose up

workflows:
  version: 2
  build-infra:
    jobs:
      - push
      - install:
          requires:
            - push