# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
aliases:
  # Filters for dev workflow
  - &dev-filter
      branches:
        only: /.*/
      tags:
        ignore: /.*/
  # Filters for prod workflow
  - &prod-filter
      branches:
        ignore: /.*/
      tags:
        only: /v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/
  # Notify when build fail on a channel discord
  - &notify_fail
        name: Notify job fail
        command: curl --data "content= error on build ${CIRCLE_BUILD_URL}" -X POST https://discordapp.com/api/webhooks/674219936931119124/LT4WVNgyN3-aW2p8oiskMhU6kNAgy9ZxrC76N_uYSzafScwAZ3SNX_aMHeHrQVEgWxlC
        when: on_fail

version: 2.1
executors:
  # Executor for install and test the application
  docker-runner:
    environment:
      PROJECT_NAME: Projet1-Team-1
    docker:
      - image: circleci/node:12.13.0
      - image: postgres
      - image: redis

  # Executor for build and publish image
  docker-publisher:
    environment:
      PROJECT_NAME: projet1-team-1
    docker:
      - image: circleci/buildpack-deps:stretch

jobs:
  # Install npm packages
  install:
    executor: docker-runner
    steps:
      - checkout
      - run:
          name: install package
          command: npm ci
      - persist_to_workspace: # Persist over jobs node_modules
          root: .
          paths:
            - ./node_modules
      - run : *notify_fail

  # Test application
  test :
    executor: docker-runner
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy node_modules
          command: cp -r /tmp/workspace/node_modules ./node_modules # Copy node_modules in app folder
      - run: npm test
      - store_artifacts:  # Export test result by artifacts
          path: test-result.txt
          destination: test-result
      - run: *notify_fail

  # Publish on docker hub an image. Image take build number for tag
  publish-image-dev :
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t api . # Build image from Dockerfile
      - run:
          name: Tag Image
          command: docker tag api ${DH_USERNAME}/${PROJECT_NAME}:${CIRCLE_BUILD_NUM} # Tag image with git tag of commit
      - run:
          name: Connect to dockerhub
          command: docker login --username=${DH_USERNAME} --password=${DH_PASSWORD}
      - run:
          name: Push on dockerhub
          command: docker push ${DH_USERNAME}/${PROJECT_NAME}:${CIRCLE_BUILD_NUM} # Push image
      - run: *notify_fail

  # Publish on docker hub an image for a release. Image take tag of release
  publish-image-prod :
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t api . # Build image from Dockerfile
      - run:
          name: Tag Image
          command: docker tag api ${DH_USERNAME}/${PROJECT_NAME}:${CIRCLE_TAG} # Tag image with git tag of commit
      - run:
          name: Connect to dockerhub
          command: docker login --username=${DH_USERNAME} --password=${DH_PASSWORD}
      - run:
          name: Push on dockerhub
          command: docker push ${DH_USERNAME}/${PROJECT_NAME}:${CIRCLE_TAG} # Push image

  # Notify when build success on a channel discord
  build-success :
    executor: docker-publisher
    steps:
      - run:
          name: Notify success
          command: curl --data "content=build success ${CIRCLE_BUILD_URL}" -X POST https://discordapp.com/api/webhooks/674219936931119124/LT4WVNgyN3-aW2p8oiskMhU6kNAgy9ZxrC76N_uYSzafScwAZ3SNX_aMHeHrQVEgWxlC
  
workflows:
  version: 2
  build-infra-dev:
    jobs:
      - install:
          filters: *dev-filter
      - test:
          filters: *dev-filter
          requires:
            - install
      - publish-image-dev:
          filters: *dev-filter
          requires:
            - test
      - build-success:
          filters: *dev-filter
          requires:
            - publish-image-dev

  build-infra-prod:
    jobs:
      - install:
          filters: *prod-filter
      - test:
          filters: *prod-filter
          requires:
            - install
      - publish-image-prod:
          filters: *prod-filter
          requires:
            - test
      - build-success:
          filters: *prod-filter
          requires:
            - publish-image-prod
